### ISSUE TITLE
C64 keys

### ISSUE THREAD

**Issue by kasbert** [sjgray/CBM-MX-Keyboards#1]
Would you be so kind that you added C64 keys to the stickers design, please ?
Namely 
 RESTORE
 CTRL (1.5u width)
 C=
 £
 [:
 ];
 f1
 f3
 f5
 f7

Would it be OK to use your keycap designs in an order to maxkeyboard or other manufacturer ?
I am planning to use those in a C64 keyboard replacement project.

**Comment by sjgray** [comment]
Yes, you can use the designs. Are you wanting PET-type stickers for a C64? The font is a bit big. I am planning on doing a C64 keyboard at some point and will scan the keycaps at that point.

**Comment by kasbert** [comment]
I am not planning to make an exact an exact copy of C64 keyboard.
So I decided to redraw the keys.
